language: go

matrix:
  include:
    - go: "tip"
    - go: "1.x"
    - go: "1.16"
    - go: "1.15"
    - go: "1.14"
    - go: "1.13"
    - go: "1.12"
    - go: "1.11"
    - go: "1.10"
    - go: "1.9"
    - go: "1.8"
  allow_failures:
    - go: tip
